spring.application.name=backend

# SQL Server Database Connection
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EventPhotographyDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
